CREATE DATABASE Babcock_University;
USE Babcock_University;

CREATE TABLE Students (
  matric_no VARCHAR(10) NOT NULL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  payment_status BOOLEAN NOT NULL,
  meal_option VARCHAR(3),
  CHECK(
    (payment_status = false AND meal_option IS NULL) OR
    (payment_status = true AND meal_option IN ('BL', 'BS', 'BLS', 'LS'))
  )
);

-- Insert 100 random students with their information
INSERT INTO Students (matric_no, name, payment_status, meal_option)
VALUES
  ('BU/18/001', 'Abdul Abdullahi', true, 'BL'),
  ('BU/18/002', 'Blessing Adeniran', false, null),
  ('BU/18/003', 'Chiamaka Adeleke', true, 'BLS'),
  ('BU/18/004', 'Daniel Adeleke', true, 'BS'),
  ('BU/18/005', 'Efe Afekhuai', false, null),
  ('BU/18/006', 'Favour Agwu', true, 'BLS'),
  ('BU/18/007', 'Grace Akinyemi', true, 'LS'),
  ('BU/18/008', 'Hassan Ali', false, null),
  ('BU/18/009', 'Ibrahim Alimi', true, 'BLS'),
  ('BU/18/010', 'Joy Aminu', true, 'BL'),
  ('BU/18/011', 'Kingsley Aneke', false, null),
  ('BU/18/012', 'Lilian Ani', true, 'LS'),
  ('BU/18/013', 'Maryam Audu', true, 'BLS'),
  ('BU/18/014', 'Nancy Babajide', false, null),
  ('BU/18/015', 'Oluwatoyin Badejo', true, 'BS'),
  ('BU/18/016', 'Peter Bakare', true, 'BLS'),
  ('BU/18/017', 'Queen Bassey', false, null),
  ('BU/18/018', 'Rosemary Brown', true, 'BLS'),
  ('BU/18/019', 'Samuel Chioma', true, 'BLS'),
  ('BU/18/020', 'Tosin Chukwuemeka', false, null),
  ('BU/18/021', 'Uche David', true, 'LS'),
  ('BU/18/022', 'Vivian Ekeh', true, 'BLS'),
  ('BU/18/023', 'Wale Eze', false, null),
  ('BU/18/024', 'Xavier Folarin', true, 'BS'),
  ('BU/18/025', 'Yemi Gabriel', true, 'BLS'),
  ('BU/18/026', 'Zainab Garba', false, null),
  ('BU/18/027', 'Abigail George', true, 'BLS'),
  ('BU/18/028', 'Benjamin Godwin', true, 'BLS'),
  ('BU/18/029', 'Chinedu Ibe', false, null),
  ('BU/18/030', 'Dorcas Ibrahim', true, 'BLS'),
  ('BU/18/031', 'Emmanuel James', true, 'LS'),
  ('BU/18/032', 'Femi Johnson', false, null),
  ('BU/18/033', 'Grace Joseph', true, 'BL'),
  ('BU/18/034', 'Hannah Kalu', true, 'BLS'),
  ('BU/18/035', 'Isaac Kazeem', false, null),
  ('BU/18/036', 'Jessica Lawal', true, 'LS'),
  ('BU/18/037', 'Kabiru Mohammed', true, 'BS'),
  ('BU/18/038', 'Linda Musa', false, null),
  ('BU/18/039', 'Mary Njoku', true, 'BLS'),
  ('BU/18/040', 'Ngozi Obi', true, 'BL'),
  ('BU/18/041', 'Ogechukwu Obi', false, null),
  ('BU/18/042', 'Precious Odu', true, 'BLS'),
  ('BU/18/043', 'Queen Ogbu', true, 'BLS'),
  ('BU/18/044', 'Rahman Olajide', false, null),
  ('BU/18/045', 'Samuel Olamide', true, 'BS'),
  ('BU/18/046', 'Tunde Olawale', true, 'BLS'),
  ('BU/18/047', 'Uchenna Onuoha', false, null),
  ('BU/18/048', 'Victoria Oyedele', true, 'LS'),
  ('BU/18/049', 'Wasiu Oyeniran', true, 'BLS'),
  ('BU/18/050', 'Xander Peters', false, null),
  ('BU/18/051', 'Yakubu Rabiu', true, 'BLS'),
  ('BU/18/052', 'Zahra Sadiq', true, 'BL'),
  ('BU/18/053', 'Adams Salisu', false, null),
  ('BU/18/054', 'Blessing Sanusi', true, 'BLS'),
  ('BU/18/055', 'Chinonso Segun', true, 'LS'),
  ('BU/18/056', 'David Shittu', false, null),
  ('BU/18/057', 'Esther Suleiman', true, 'BLS'),
  ('BU/18/058', 'Fatima Tanko', true, 'BS'),
  ('BU/18/059', 'Grace Uche', false, null),
  ('BU/18/060', 'Henry Udo', true, 'BLS'),
  ('BU/18/061', 'Ijeoma Ukaegbu', true, 'BLS'),
  ('BU/18/062', 'Johnson Umeh', false, null),
  ('BU/18/063', 'Kemi Victor', true, 'LS'),
  ('BU/18/064', 'Lucas Yakubu', true, 'BLS'),
  ('BU/18/065', 'Maryam Yusuf', false, null),
  ('BU/18/066', 'Nancy Zainab', true, 'BLS'),
  ('BU/18/067', 'Oluwatobi Zara', true, 'BL'),
  ('BU/18/068', 'Pauline Zaria', false, null),
  ('BU/18/069', 'Qudus Zikirullahi', true, 'BLS'),
  ('BU/18/070', 'Ruth Zion', true, 'BS'),
  ('BU/18/071', 'Sadiq Zuwaira', false, null),
  ('BU/18/072', 'Abdullahi Abdulrahman', true, 'LS'),
  ('BU/18/073', 'Babatunde Balogun', true, 'BLS'),
  ('BU/18/074', 'Chidinma Chukwu', false, null),
  ('BU/18/075', 'Daniel Dauda', true, 'BLS'),
  ('BU/18/076', 'Emmanuel Eze', true, 'BL'),
  ('BU/18/077', 'Fatimah Femi', false, null),
  ('BU/18/078', 'Gloria Godwin', true, 'BLS'),
  ('BU/18/079', 'Hassan Habib', true, 'BS'),
  ('BU/18/080', 'Ibrahim Idris', false, null),
  ('BU/18/081', 'Jennifer John', true, 'BLS'),
  ('BU/18/082', 'Kabiru Kazeem', true, 'BLS'),
  ('BU/18/083', 'Lilian Lawal', false, null),
  ('BU/18/084', 'Musa Mohammed', true, 'BL'),
  ('BU/18/085', 'Nkechi Nnamdi', true, 'BLS'),
  ('BU/18/086', 'Olawale Ojo', false, null),
  ('BU/18/087', 'Precious Peters', true, 'BLS'),
  ('BU/18/088', 'Queen Raphael', true, 'BS'),
  ('BU/18/089', 'Raphael Samuel', false, null),
  ('BU/18/090', 'Samuel Smith', true, 'BLS'),
  ('BU/18/091', 'Tolu Taiwo', true, 'BLS'),
  ('BU/18/092', 'Umaru Umar', false, null),
  ('BU/18/093', 'Victoria Victor', true, 'BL'),
  ('BU/18/094', 'Wale Williams', true, 'BLS'),
  ('BU/18/095', 'Xavier Yakubu', false, null),
  ('BU/18/096', 'Yemi Yusuf', true, 'BLS'),
  ('BU/18/097', 'Zainab Zakari', true, 'BLS'),
  ('BU/18/098', 'Abdul Zara', false, null),
  ('BU/18/099', 'Blessing Zainab', true, 'LS'),
  ('BU/18/100', 'Chika Zion', true, 'BLS');
  
